# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serverer', '0003_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
