# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serverer', '0004_auto_20180220_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
