# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serverer', '0005_delete_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
