# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serverer', '0006_song_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='file_hash',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
